package plateau.action;
import plateau.gamecharacter.Survivor;

/**
 * Abstract class representing an action that can be performed by a survivor.
 */
public abstract class Action {
    

    /** 
     * Cost in action points (default = 1) 
    */
    public int cost() { 
        return 1; 
    } 
    
    /** 
    * Noise generated by the action (default = 0)
    */ 
    public int noise() { 
        return 0; 
    }

    /**
     * Executes the action on the given survivor.
     *
     * @param s The survivor on which the action is to be executed.
     */
    public abstract void execute(Survivor s);
    
    /**
     * Returns a string representation of the action.
     *
     * @return A string describing the action.
     */
    public abstract String toString();

    
}